import React, { useState } from 'react'
import type { AgentSpec } from '@repo/types'
import {
  RiCloseLine,
  RiFileCopyLine,
  RiCheckLine,
  RiDownloadLine,
  RiTerminalBoxLine,
  RiCodeSSlashLine,
  RiCpuLine,
} from 'react-icons/ri'

interface ExportModalProps {
  isOpen: boolean
  onClose: () => void
  agent?: AgentSpec
}

export const ExportModal: React.FC<ExportModalProps> = ({
  isOpen,
  onClose,
  agent,
}) => {
  const [activeTab, setActiveTab] = useState<'eve' | 'python' | 'json' | 'ao'>(
    'eve',
  )
  const [copied, setCopied] = useState(false)

  if (!isOpen || !agent) return null

  const generateEveSpec = (a: AgentSpec) => {
    return `# EVE AGENT SPECIFICATION
name: ${a.name}
domain: ${a.domain}
architecture: ${a.architectureSummary}

## System Instructions
You are ${a.name}, an autonomous specialized AI agent engineered through OpenBot meta-optimization.

### Pipeline Stages & Roles
${a.nodes
  .map(
    (n, i) => `${i + 1}. **${n.name}** (${n.role})
   - Prompt: ${n.systemPrompt}
   - Assigned Tools: ${n.assignedTools.length > 0 ? n.assignedTools.join(', ') : 'None'}`,
  )
  .join('\n\n')}

### Tools Configuration
${JSON.stringify(
  a.nodes
    .flatMap((n) => n.assignedTools)
    .filter((v, i, arr) => arr.indexOf(v) === i),
  null,
  2,
)}
`
  }

  const generatePythonSpec = (a: AgentSpec) => {
    return `"""
Autonomously Engineered Agent: ${a.name}
Domain: ${a.domain.toUpperCase()}
Architecture: ${a.architectureSummary}
Generated by OpenBot
"""

import asyncio
from typing import Dict, Any, List
from dataclasses import dataclass

@dataclass
class AgentState:
    query: str
    intermediate_data: Dict[str, Any]
    verified_evidence: List[str]
    final_output: str

class ${a.name.replace(/[^a-zA-Z0-9]/g, '')}:
    def __init__(self):
        self.stages = [
${a.nodes.map((n) => `            {"name": "${n.name}", "role": "${n.role}", "tools": ${JSON.stringify(n.assignedTools)}}`).join(',\n')}
        ]

    async def execute(self, query: str) -> str:
        state = AgentState(query=query, intermediate_data={}, verified_evidence=[], final_output="")
        print(f"[*] Executing pipeline: {self.stages}")
${a.nodes
  .map(
    (n, i) => `        # Stage ${i + 1}: ${n.name}
        state.intermediate_data["${n.id}"] = await self._run_${n.id.replace(/-/g, '_')}(state)`,
  )
  .join('\n')}
        return state.intermediate_data["${a.nodes[a.nodes.length - 1]?.id}"]

${a.nodes
  .map(
    (
      n,
    ) => `    async def _run_${n.id.replace(/-/g, '_')}(self, state: AgentState):
        # Prompt: ${n.systemPrompt.replace(/\n/g, ' ')}
        return f"[Completed ${n.name} execution for {state.query}]"`,
  )
  .join('\n\n')}

if __name__ == "__main__":
    agent = ${a.name.replace(/[^a-zA-Z0-9]/g, '')}()
    result = asyncio.run(agent.execute("Analyze recent AI benchmark results"))
    print(result)
`
  }

  const generateAoSpec = (a: AgentSpec) => {
    return JSON.stringify(
      {
        ao_schema_version: '2.1',
        orchestrator: 'AgentOrchestrator-Core',
        agent_id: a.id,
        name: a.name,
        domain: a.domain,
        execution_graph: {
          nodes: a.nodes.map((n) => ({
            node_id: n.id,
            display_name: n.name,
            worker_type: n.role,
            system_prompt: n.systemPrompt,
            allowed_tools: n.assignedTools,
          })),
          edges: a.edges.map((e) => ({
            from_stage: e.source,
            to_stage: e.target,
          })),
        },
      },
      null,
      2,
    )
  }

  const getContent = () => {
    switch (activeTab) {
      case 'eve':
        return generateEveSpec(agent)
      case 'python':
        return generatePythonSpec(agent)
      case 'ao':
        return generateAoSpec(agent)
      case 'json':
        return JSON.stringify(agent, null, 2)
    }
  }

  const handleCopy = () => {
    navigator.clipboard.writeText(getContent())
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleDownload = () => {
    const ext =
      activeTab === 'python' ? 'py' : activeTab === 'eve' ? 'md' : 'json'
    const filename = `${agent.name.toLowerCase().replace(/[^a-z0-9]/g, '-')}.${ext}`
    const blob = new Blob([getContent()], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = filename
    link.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-xs p-4">
      <div className="flex flex-col w-full max-w-3xl max-h-[85vh] bg-card border border-border rounded-xl shadow-2xl overflow-hidden text-foreground font-sans animate-in fade-in zoom-in-95 duration-200">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-border bg-card">
          <div>
            <div className="flex items-center gap-2">
              <h3 className="text-base font-semibold text-foreground">
                Export Specialist Agent
              </h3>
              <span className="px-2 py-0.5 rounded text-[11px] font-mono font-medium bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
                Verified & Ready
              </span>
            </div>
            <p className="text-xs text-muted-foreground mt-0.5">
              {agent.name} • {agent.architectureSummary}
            </p>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-md text-muted-foreground hover:text-foreground hover:bg-muted transition-colors cursor-pointer"
          >
            <RiCloseLine className="w-5 h-5" />
          </button>
        </div>

        {/* Tab Selection */}
        <div className="flex items-center justify-between px-6 py-2.5 bg-muted/40 border-b border-border">
          <div className="flex items-center gap-1.5">
            <button
              onClick={() => setActiveTab('eve')}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium transition-all cursor-pointer ${
                activeTab === 'eve'
                  ? 'bg-background text-foreground shadow-xs border border-border/50'
                  : 'text-muted-foreground hover:text-foreground hover:bg-muted/60'
              }`}
            >
              <RiCpuLine className="w-3.5 h-3.5" />
              <span>Eve Spec (.md)</span>
            </button>
            <button
              onClick={() => setActiveTab('ao')}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium transition-all cursor-pointer ${
                activeTab === 'ao'
                  ? 'bg-background text-foreground shadow-xs border border-border/50'
                  : 'text-muted-foreground hover:text-foreground hover:bg-muted/60'
              }`}
            >
              <RiTerminalBoxLine className="w-3.5 h-3.5" />
              <span>Runtime Spec</span>
            </button>
            <button
              onClick={() => setActiveTab('python')}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium transition-all cursor-pointer ${
                activeTab === 'python'
                  ? 'bg-background text-foreground shadow-xs border border-border/50'
                  : 'text-muted-foreground hover:text-foreground hover:bg-muted/60'
              }`}
            >
              <RiCodeSSlashLine className="w-3.5 h-3.5" />
              <span>Python DAG (.py)</span>
            </button>
            <button
              onClick={() => setActiveTab('json')}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium transition-all cursor-pointer ${
                activeTab === 'json'
                  ? 'bg-background text-foreground shadow-xs border border-border/50'
                  : 'text-muted-foreground hover:text-foreground hover:bg-muted/60'
              }`}
            >
              <span>AgentSpec (.json)</span>
            </button>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-secondary hover:bg-secondary/80 text-secondary-foreground text-xs font-medium border border-border transition-colors cursor-pointer"
            >
              {copied ? (
                <RiCheckLine className="w-3.5 h-3.5 text-emerald-400" />
              ) : (
                <RiFileCopyLine className="w-3.5 h-3.5" />
              )}
              <span>{copied ? 'Copied!' : 'Copy'}</span>
            </button>
            <button
              onClick={handleDownload}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-primary hover:bg-primary/90 text-primary-foreground text-xs font-semibold transition-colors shadow-xs cursor-pointer"
            >
              <RiDownloadLine className="w-3.5 h-3.5" />
              <span>Download</span>
            </button>
          </div>
        </div>

        {/* Code Content View */}
        <div className="flex-1 overflow-auto p-4 bg-muted/20 font-mono text-xs text-foreground/90 leading-relaxed select-all">
          <pre className="whitespace-pre-wrap">{getContent()}</pre>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between px-6 py-3 border-t border-border bg-card text-xs text-muted-foreground">
          <span>Deployable to production environments</span>
          <button
            onClick={onClose}
            className="px-3 py-1 rounded-md bg-secondary hover:bg-secondary/80 text-secondary-foreground border border-border transition-colors cursor-pointer"
          >
            Done
          </button>
        </div>
      </div>
    </div>
  )
}
