/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProtectedBillingRouteImport } from './routes/_protected/billing'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as OffersFormIdRouteImport } from './routes/offers/$formId'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as StudioAgentIdRouteImport } from './routes/studio/$agentId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiWebhookDodoRouteImport } from './routes/api/webhook/dodo'
import { Route as ProtectedFormsFormIdIndexRouteImport } from './routes/_protected/forms/$formId/index'
import { Route as ProtectedFormsFormIdResponsesRouteImport } from './routes/_protected/forms/$formId/responses'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedBillingRoute = ProtectedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersFormIdRoute = OffersFormIdRouteImport.update({
  id: '/offers/$formId',
  path: '/offers/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioAgentIdRoute = StudioAgentIdRouteImport.update({
  id: '/studio/$agentId',
  path: '/studio/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookDodoRoute = ApiWebhookDodoRouteImport.update({
  id: '/api/webhook/dodo',
  path: '/api/webhook/dodo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedFormsFormIdIndexRoute =
  ProtectedFormsFormIdIndexRouteImport.update({
    id: '/forms/$formId/',
    path: '/forms/$formId/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedFormsFormIdResponsesRoute =
  ProtectedFormsFormIdResponsesRouteImport.update({
    id: '/forms/$formId/responses',
    path: '/forms/$formId/responses',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/billing': typeof ProtectedBillingRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/api/$': typeof ApiSplatRoute
  '/offers/$formId': typeof OffersFormIdRoute
  '/studio/$agentId': typeof StudioAgentIdRoute
  '/studio/': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/webhook/dodo': typeof ApiWebhookDodoRoute
  '/forms/$formId/responses': typeof ProtectedFormsFormIdResponsesRoute
  '/forms/$formId/': typeof ProtectedFormsFormIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/billing': typeof ProtectedBillingRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/api/$': typeof ApiSplatRoute
  '/offers/$formId': typeof OffersFormIdRoute
  '/studio/$agentId': typeof StudioAgentIdRoute
  '/studio': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/webhook/dodo': typeof ApiWebhookDodoRoute
  '/forms/$formId/responses': typeof ProtectedFormsFormIdResponsesRoute
  '/forms/$formId': typeof ProtectedFormsFormIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/_protected/billing': typeof ProtectedBillingRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/api/$': typeof ApiSplatRoute
  '/offers/$formId': typeof OffersFormIdRoute
  '/studio/$agentId': typeof StudioAgentIdRoute
  '/studio/': typeof StudioIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/webhook/dodo': typeof ApiWebhookDodoRoute
  '/_protected/forms/$formId/responses': typeof ProtectedFormsFormIdResponsesRoute
  '/_protected/forms/$formId/': typeof ProtectedFormsFormIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pricing'
    | '/billing'
    | '/dashboard'
    | '/api/$'
    | '/offers/$formId'
    | '/studio/$agentId'
    | '/studio/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/webhook/dodo'
    | '/forms/$formId/responses'
    | '/forms/$formId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pricing'
    | '/billing'
    | '/dashboard'
    | '/api/$'
    | '/offers/$formId'
    | '/studio/$agentId'
    | '/studio'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/webhook/dodo'
    | '/forms/$formId/responses'
    | '/forms/$formId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/pricing'
    | '/_protected/billing'
    | '/_protected/dashboard'
    | '/api/$'
    | '/offers/$formId'
    | '/studio/$agentId'
    | '/studio/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/webhook/dodo'
    | '/_protected/forms/$formId/responses'
    | '/_protected/forms/$formId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ApiSplatRoute: typeof ApiSplatRoute
  OffersFormIdRoute: typeof OffersFormIdRoute
  StudioAgentIdRoute: typeof StudioAgentIdRoute
  StudioIndexRoute: typeof StudioIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiWebhookDodoRoute: typeof ApiWebhookDodoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/billing': {
      id: '/_protected/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof ProtectedBillingRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/$formId': {
      id: '/offers/$formId'
      path: '/offers/$formId'
      fullPath: '/offers/$formId'
      preLoaderRoute: typeof OffersFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$agentId': {
      id: '/studio/$agentId'
      path: '/studio/$agentId'
      fullPath: '/studio/$agentId'
      preLoaderRoute: typeof StudioAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/dodo': {
      id: '/api/webhook/dodo'
      path: '/api/webhook/dodo'
      fullPath: '/api/webhook/dodo'
      preLoaderRoute: typeof ApiWebhookDodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/forms/$formId/': {
      id: '/_protected/forms/$formId/'
      path: '/forms/$formId'
      fullPath: '/forms/$formId/'
      preLoaderRoute: typeof ProtectedFormsFormIdIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/forms/$formId/responses': {
      id: '/_protected/forms/$formId/responses'
      path: '/forms/$formId/responses'
      fullPath: '/forms/$formId/responses'
      preLoaderRoute: typeof ProtectedFormsFormIdResponsesRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedBillingRoute: typeof ProtectedBillingRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedFormsFormIdResponsesRoute: typeof ProtectedFormsFormIdResponsesRoute
  ProtectedFormsFormIdIndexRoute: typeof ProtectedFormsFormIdIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedBillingRoute: ProtectedBillingRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedFormsFormIdResponsesRoute: ProtectedFormsFormIdResponsesRoute,
  ProtectedFormsFormIdIndexRoute: ProtectedFormsFormIdIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ApiSplatRoute: ApiSplatRoute,
  OffersFormIdRoute: OffersFormIdRoute,
  StudioAgentIdRoute: StudioAgentIdRoute,
  StudioIndexRoute: StudioIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiWebhookDodoRoute: ApiWebhookDodoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
