import type { ToolDefinition } from "@repo/types";

export const availableTools: ToolDefinition[] = [
  // Research Tools
  {
    id: "tool-web-search",
    name: "Real-Time Web Search",
    description: "Performs real-time web search and crawls ranked serp results.",
    parameters: {},
    category: "search",
    isMock: false,
    requiredEnvs: [],
  },
  {
    id: "tool-content-scraper",
    name: "Web Content Scraper",
    description: "Extracts clean readable markdown and text from web pages.",
    parameters: {},
    category: "retrieval",
    isMock: false,
    requiredEnvs: [],
  },
  {
    id: "tool-source-verifier",
    name: "Evidence Cross-Verifier",
    description: "Cross-checks facts against independent repositories, academic papers, and benchmark databases.",
    parameters: {},
    category: "verification",
    isMock: false,
    requiredEnvs: [],
  },
  // Coding Tools
  {
    id: "tool-ast-investigator",
    name: "Codebase AST Analyzer",
    description: "Parses Abstract Syntax Trees, traces call graphs and symbol declarations across files.",
    parameters: {},
    category: "code",
    isMock: false,
    requiredEnvs: [],
  },
  {
    id: "tool-test-runner",
    name: "Sandbox Test Runner",
    description: "Executes unit and integration test suites in an isolated sandbox and captures traces.",
    parameters: {},
    category: "code",
    isMock: false,
    requiredEnvs: [],
  },
  {
    id: "tool-git-patcher",
    name: "Git Diff & Patch Engine",
    description: "Generates atomic unified git diffs and verifies patch application cleanly.",
    parameters: {},
    category: "code",
    isMock: false,
    requiredEnvs: [],
  },
  // Finance & Data Tools
  {
    id: "tool-csv-loader",
    name: "Vectorized Data Ingester",
    description: "Ingests structured tabular datasets, normalizes currencies, and cleans date formatting.",
    parameters: {},
    category: "data",
    isMock: false,
    requiredEnvs: [],
  },
  {
    id: "tool-iqr-anomaly-detector",
    name: "Statistical Anomaly Detector",
    description: "Detects numerical and categorical policy outliers using rolling interquartile ranges.",
    parameters: {},
    category: "data",
    isMock: false,
    requiredEnvs: [],
  },
  {
    id: "tool-compliance-checker",
    name: "Policy Compliance Auditor",
    description: "Validates transaction metadata against company governance limits and procurement clauses.",
    parameters: {},
    category: "verification",
    isMock: false,
    requiredEnvs: [],
  },
  // Third-Party Integrations & Dispatchers
  {
    id: "tool-slack-notifier",
    name: "Slack Channel Notifier",
    description: "Dispatches formatted alerts, digests, and interactive blocks to Slack via Incoming Webhook.",
    parameters: {},
    category: "utility",
    isMock: false,
    requiredEnvs: ["SLACK_WEBHOOK_URL"],
  },
  {
    id: "tool-discord-notifier",
    name: "Discord Channel Notifier",
    description: "Dispatches formatted markdown embeds to Discord channels via Incoming Webhook.",
    parameters: {},
    category: "utility",
    isMock: false,
    requiredEnvs: ["DISCORD_WEBHOOK_URL"],
  },
  {
    id: "tool-github-api",
    name: "GitHub Repository API",
    description: "Interacts with GitHub repos, issues, pull requests, and commit histories via GitHub API.",
    parameters: {},
    category: "code",
    isMock: false,
    requiredEnvs: ["GITHUB_TOKEN"],
  },
  {
    id: "tool-twitter-x",
    name: "X / Twitter Search & Stream API",
    description: "Pulls real-time posts, threads, user mentions, and search queries via X Bearer Token.",
    parameters: {},
    category: "search",
    isMock: false,
    requiredEnvs: ["TWITTER_BEARER_TOKEN"],
  },
  {
    id: "tool-firecrawl",
    name: "Firecrawl Deep Scraper",
    description: "Crawls entire domains, handles JavaScript-heavy single-page apps, and extracts clean markdown.",
    parameters: {},
    category: "retrieval",
    isMock: false,
    requiredEnvs: ["FIRECRAWL_API_KEY"],
  },
  {
    id: "tool-webhook-dispatch",
    name: "Custom Webhook Dispatcher",
    description: "Dispatches real-time JSON payloads to any external REST endpoint or server webhook.",
    parameters: {},
    category: "utility",
    isMock: false,
    requiredEnvs: ["WEBHOOK_URL"],
  },
];

export function getToolById(id: string): ToolDefinition | undefined {
  return availableTools.find((t) => t.id === id);
}
